server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: ai-agent

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}

    streams:
      application-id: ai-agent-stream

    consumer:
      group-id: ai-agent
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: backend.academy.linktracker.ai.dto.AggregatedNotification

    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}


logging:
  level:
    backend.academy.linktracker.ai: DEBUG

app:
  filter:
    stop-words:
      - spam
      - ads
      - promo
    excluded-authors:
      - bot-user
    min-length: 20

  ai:
    url: ${AI_URL:https://router.huggingface.co/v1/chat/completions}
    token: ${AI_TOKEN:test_token}
    model: "deepseek-ai/DeepSeek-V4-Pro:novita"
    threshold: 200
    query:
      prompt: "Summarize the following update in 2–3 sentences:\n\n"
      role: "user"

  prioritization:

    high-keywords:
      - critical
      - urgent
      - breaking
      - security
    low-keywords:
      - minor
      - typo
      - chore
      - docs

  grouping:
    window-ms: 30000

  kafka:
    raw-updates-topic: ${RAW_UPDATES_TOPIC_NAME:raw-updates}
    processed-updates-topic: ${PROCESSED_UPDATES_TOPIC_NAME:processed-updates}
    aggregated-updates-topic: ${AGGREGATED_UPDATES_TOPIC:aggregated-updates-topic}
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://schema-registry:8081}
    replicas: ${REPLICA_FACTOR:1}
    partitions: ${PARTITION_FACTOR:1}

