server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: scrapper

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 2
    properties:
      spring.json.add.type.headers: false
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      jdbc:
        batch_size: ${app.batch-size}
        order_inserts: true
        order_updates: true
  data:
    redis:
      cluster:
        nodes: ${CACHE_CLUSTER_NODES:localhost:6371,localhost:6372,localhost:6373}


logging:
  file:
    name: scrapper/log/application.log
  structured:
    format:
      file: ecs

app:
  db-provider: orm
  retryable-statuses: 500,502,503,504

  kafka:
    topic-name: ${APP_TOPIC_NAME:link-updates}
    replicas: ${REPLICA_FACTOR:1}
    partitions: ${PARTITION_FACTOR:1}
    dlq-topic-name: ${DLQ_TOPIC_NAME:link-updates-dlq}

  scrapper-settings:
    check-link-interval: 3000
    check-outbox-interval: 1000
    age-of-links: 6000
    number-of-threads: 4
    batch-size: 100

  cache:
    ttl: 36000
    max-size-local-cache: 10000


  bot:
    base-url: ${APP_TELEGRAM_BOT_BASE_URL:https://bot:8080}
    connection-timeout: 100
    response-timeout: 50

  stackoverflow:
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}
    base-url: https://api.stackexchange.com
    connection-timeout: 300
    response-timeout: 200

  github:
    token: ${GITHUB_TOKEN}
    base-url: https://api.github.com
    connection-timeout: 300
    response-timeout: 200


resilience4j:
  retry:
    instances:
      github:
        max-attempts: 2
        wait-duration: 1s

      stackoverflow:
        max-attempts: 2
        wait-duration: 1s

      bot:
        max-attempts: 2
        wait-duration: 1s
  ratelimiter:
    configs:
      ip-limit:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 0s



