server:
  port: 8081

spring:
  application:
    name: scrapper

app:
  shedulerinterval:
    6000
  stackoverflow:
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: https://api.stackexchange.com
    question-endpoint: /questions/{id}

  github:
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: https://api.github.com
    issues-endpoint: /repos/{owner}/{repo}/issues

  telegram-bot:
    base-url: http://localhost:8080
    update-endpoint: /updates
