server:
  port: 8080

spring:
  application:
    name: bot

logging:
  file:
    name: bot/log/application.log
  structured:
    format:
      file: ecs

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_BOT_TOKEN}
    update-listener-sleep: 1s
    debug: false

  scrapper:
    base-url: http//:localhost:8081
    chat-endpoint: /tg-chat/
    links-endpoint: /links
