server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: bot

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: telegram-bot-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
        specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}

logging:
  file:
    name: bot/log/application.log
  structured:
    format:
      file: ecs

app:
  cache:
    rate-limiter:
      max-size: 10000
      ttl: 1
    idempotency-key:
      max-size: 10000
      ttl: 24

  retryable-statuses: 500, 501, 502, 503, 504

  kafka:
    topic-name: ${APP_TOPIC_NAME:link-updates}
    retries: 3
    timeout: 6000

  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_BOT_TOKEN}
    update-listener-sleep: 1s
    connection-timeout: 5000
    write-timeout: 75
    read-timeout: 75
    debug: false

  scrapper:
    base-url: ${APP_SCRAPPER_BASE_URL:https://scrapper:8081}
    connection-timeout: 500
    response-timeout: 2000

resilience4j:
  retry:
    instances:
      scrapper:
        max-attempts: 2
        wait-duration: 1s

      telegram:
        max-attempts: 2
        wait-duration: 1s

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      filter-method: servlet
      filter-order: -1
      url: .*
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 50
              time: 10
              unit: seconds
      http-response-body: "{ \"error\": \"Too many requests\" }"
