server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: bot

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: telegram-bot-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: backend.academy.linktracker.bot.dto.LinkUpdate

logging:
  file:
    name: bot/log/application.log
  structured:
    format:
      file: ecs

app:
  kafka:
    topic-name: ${APP_TOPIC_NAME:link-updates}
    max-retries: ${RETRIES_COUNT:3}
    time-out: ${TIME_OUT:6000}

  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_BOT_TOKEN}
    update-listener-sleep: 1s
    debug: false

  scrapper:
    base-url: ${APP_SCRAPPER_BASE_URL:https://scrapper:8081}
