{
    "type": "record",
    "name": "ProcessedLinkUpdate",
    "namespace": "backend.academy.linktracker.avro",
    "fields": [
        {
            "name": "idempotenceKey",
            "type": {
                "type": "string",
                "logicalType": "uuid"
            },
            "doc": "Ключ идемпотентности для bot service"
        },
        {
            "name": "linksIds",
            "type": {
                "type": "array",
                "items": "long"
            },
            "doc": "ID ссылок"
        },
        {
            "name": "description",
            "type": "string",
            "doc": "Описание изменений"
        },
        {
            "name": "tgChatId",
            "type": "long",
            "doc": "ID чата"
        }
    ]
}
